### ISSUE TITLE
Applying mapplate to csv file

### ISSUE THREAD

**Issue by stork119** [stork119/PathwayPackage#104]
Function _prepare_mp_output(input_data, mp_dict, mp_key):

There is no other method to operate on matrices in python ? Check numpy package

**Comment by Setnea** [comment]
Well, there is, but I'm treating all our csvs as list of the lists, which makes getting line of well names or well params super easy aand I can use already existing fucntions such as: 

> def get_well_params(mp_dict, well):
>     """ 
>     Gives all parameters values for a given well
>     """
>     values = []
>     for param in mp_dict[well]:
>         values.append(mp_dict[well][param])
>     return values

and 

> def get_params_names(mp_dict): # get all key names from map_plate dictionary
>     names = []
>     key_0 = list(mp_dict.keys())[0]
>     names = list(mp_dict[key_0].keys())

**Comment by Setnea** [comment]
and I can use already existing fucntions such as: def get_well_params(mp_dict, well):
    """ 
    Gives all parameters values for a given well
    """
    values = []
    for param in mp_dict[well]:
        values.append(mp_dict[well][param])
    return values

**Comment by stork119** [comment]
@Setnea 👍
