### ISSUE TITLE
Generic function for collecting tasks argumnets

### ISSUE THREAD

**Issue by stork119** [stork119/PathwayPackage#105]
1. Create function `parse_task_arguments` ( function name can be changed ), that check if arguments are in dict_local and if not use default values. 
2. Function can be moved to main class TASK 
3. Function has many repeated statements. Code can be easily simplified.
4. Add position in TASK: 
    task_arguments = dict( argument_name : <default_value, required> ),
    - required - false if argument is optional to pass by user
                     - true, if argument is required by user
    - if optional == true & argument did not found in dict_local then throw error
5. def parse_task_arguments(dict_local): 
    ```for task_arg in task_arguments :
         dict_task = dict()
         try:
             dict_task[task[key]] = dict_local[task[key]]
         except:
             if dict_local[task[required]]:
                  throw error
             else: 
                  dict_task[task[key]] = task[default]
      ```
      return(dict_task)

**Comment by stork119** [comment]
In parallel do task #110

**Comment by Setnea** [comment]
#100 duplicated. I'm closing #100 due to this issue provide more usufull info and there is no need to keep them both.

**Comment by stork119** [comment]
@Setnea  according to your question: 
http://stackoverflow.com/questions/867219/python-class-members-initialization

Declaring a dict outside of __init__ as you initially did is declaring a class-level variable. It is only created once at first, whenever you create new objects it will reuse this same dict. To create instance variables, you declare them with self in __init__; its as simple as that.

And this is what we want to do.
