### ISSUE TITLE
External config dictionary for computer arguments

### ISSUE THREAD

**Issue by stork119** [stork119/PathwayPackage#111]
- Add possibility to load xml with configuration arguments.
- Add loading of IPIQA config  at the beginning of program execution
- Create folder with configs file:
```
configs/
```
- create default config `IPIQA.xml`, that consists these arguments that are dedicated to computer.
- add parsed argument to program '-c [config]' that is a directory for configuration files.

**Comment by Setnea** [comment]
@stork119 
To reconsider- which config_dict should overwrite the second one.

**Comment by stork119** [comment]
@Setnea I think that load order should be as follow: 

1. computer config (config/IPIQA.xml as default)
2. experiment xml  
3. additional arguments passed in command line 

For simplicity, we can assume that xml parameters could be overwritten

**Comment by Setnea** [comment]
The load order meets your requirments, I removed no longer needed, commented code.

**Comment by stork119** [comment]
@Setnea this feature does not work on FISHER PC

**Comment by Setnea** [comment]
Strange I was using it when I was running tests on fisher pc. What exacly doesn't work?

**Comment by Setnea** [comment]
Default path to config dict - IPIQA/configs/ and optionally changed by parsing argument using -c

**Comment by Setnea** [comment]
Issue can be closed.
