### ISSUE TITLE
[XML] Variable class 

### ISSUE THREAD

**Issue by stork119** [stork119/PathwayPackage#120]
This task is part of task #70 

1. Create class Variable that represents objects in the IPIQA'a environment (env_global, env_local). 

```
class Variable():
  def __init__(key, value, args = {})
  def get_value(env, args = {})
  def set_value(value, args = {})
```

2. Create class VariableReference that inherit from Variable class and represents references  in the IPIQA'a environment (env_global, env_local). Now, we have

```
class VariableReference(Variable):
  def get_value(env, args = {}):
    return env[value].get_value(env, args)
```

3.  Join 'by_name' and 'by_value' parameters/updates:

<parameter/update key = "", value = "",  type = (any if by value | "reference" for previous by name> >

4. env_global = { key = Variable(key, value,  args = {}} 

5. args are additional arguments that will be used in next features

**Comment by Setnea** [comment]
Variable class to work fully properly requires changes pointe at following issues:
- #134 [solved]
- #133 [solved]
- #127 [in progress]
Changes will be apply on branch xml_variable_hotfix.
