### ISSUE TITLE
Add parameter type list

### ISSUE THREAD

**Issue by stork119** [stork119/PathwayPackage#136]
- Create new name for class VariableList
- Create new XML parameter type list that contains parameters 
- Structure of XML is following
```
<parameter key = "<KEY>" type = "list">
  <value>
    <parameter key = "<KEY>" value = "<VALUE>" type = "<TYPE>">
  <value/>
<parameter>
```
- Create Class VariableList that map xml object on IPIQA environment

**Comment by Setnea** [comment]
For me it looks like very specific task_for structure not general "list" structure (which can be use also in other cases). I think we missunderstood each other on last meeting.

**Comment by Setnea** [comment]
According to our discussion, current VariableList presents as following:

```
<parameter key = "<KEY>" type = "list">
    <parameter value = "<VALUE>" type = "<TYPE>">
    <parameter value = "<VALUE>" type = "<TYPE>">
<parameter>
```
