### ISSUE TITLE
Add opportunity to run for loop on parameters list 

### ISSUE THREAD

**Issue by stork119** [stork119/PathwayPackage#137]
- Scheme in the xml : 
```
<TASK_FOR>
    <VARIABLES key = <parameter_list_key>/> 
</TASK_FOR>
```
<parameter_list_key> is a key of parameter of type 'list' - if not throw error.

- Object <parameter_list_key> is a list of objects of ANY type ( not only VariableStructure ). 
- You have to consider how to iterate on elements of <parameter_list> 
- In each turn of the loop you should add to env_local parameters from variable that is on the ith position in <parameter_list>

Use for it function '''create_dict()''', that look as follow: 
'''
class Variable():
  def create_dict():
    return dict( self.key = self.value )
'''
This function is overload in class VariableStructure: 
'''
class VariableStructure(Variable):
  def create_dict():
  // create dictionary that consists of all parameters in this structure
'''

Next, create function that merge env_local with dictionary returned from function create_dict

- remember not to remove position key from class Variable

**Comment by Setnea** [comment]
Just one comment:
create_dict() have to return dictionary of variables, not dictionary of values, because our environments (which we would like to update) are represented by variables. 

I just implemented it like that:

```
class Variable()
    def create_dict(self, env):
        return {self.key : self.get_variable(env)}

class VariableStructure()
    def create_dict(self, env):
        return self

```

**Comment by Setnea** [comment]
I'm not fully satisfied with current solution for TASK_FOR (specially modyfication on VariableList), by now everything works fine, but I would like to discuss issue tomorrow, for more details see pull request #152.
