### ISSUE TITLE
[XML] add type structure

### ISSUE THREAD

**Issue by stork119** [stork119/PathwayPackage#147]
Add parameter type structure to xml settings
```
<parameter key = "<KEY>" type = "structure">
  <value>
    <parameter key = "<KEY>" value = "<VALUE>" type = "<TYPE>">
    <parameter key = "<KEY2>" value = "<VALUE2>" type = "<TYPE>">
  <value/>
<parameter>
```
Create class VariableStructure that map parameter of type structure.
Class should be implemented analogously to VariableMapPlate.

**Comment by Setnea** [comment]
I have a proposal to change name "value" to "set", because this xml structure represents sets of values (parameters). Name "value" is super missleading and we use it for many other instances in ours software. @stork119 what do you think? Maybe there is even better alternative

**Comment by Setnea** [comment]
According to our conversation structure will look as following:

```
<parameter key = "<KEY>" type = "structure">
    <parameter key = "<KEY>" value = "<VALUE>" type = "<TYPE>">
    <parameter key = "<KEY2>" value = "<VALUE2>" type = "<TYPE>">
<parameter>
```
