### ISSUE TITLE
[XML] merge_csv_subdir basing on parameter of type list

### ISSUE THREAD

**Issue by stork119** [stork119/PathwayPackage#148]
- parameter <csv_names_list> should be of type 'list'
- add try except structure in the loop as follow:

'''
for csv in csv_name_list 
  try:
    // merge
  except:
     logger.warning()
     pass
'''

**Comment by Setnea** [comment]
Btw I noticed that we filter out list of directories containing given csv file. So there is no problem if some of wells do not contain specific data (i.e. Nuclei.csv file). Just pointing.
