### ISSUE TITLE
[MAPPLATE] Additional functions for processing collected information

### ISSUE THREAD

**Issue by Setnea** [stork119/PathwayPackage#64]
Module requires additional functions for processing collected in dictionary information about all wells.

**Comment by stork119** [comment]
Please, add description of these functions. 
NAME( PARAMETERS ) -- fucntionality

**Comment by Setnea** [comment]
Example of mp_dictionary = {"A01" :  {"position" : [0,0], "name" : "A01", "cells" : "A549"} , "B02" : {"position" : [1,1], "name" : "B02", "cells" : "A549"} }, where:
- A01, B02- well names
- position, name, cells- parameters
- [0,0], A01, A549, [1,1], B02, A549- values of given parameters

1. get_param_value(mp_dictionary, well_name, parameter)
Get value for a given well and parameter

2. get_param_all_values(mp_dictionary, parameter)
Get all values for a given param from map_plate dictionary

3. get_param_unique_values(mp_dictionary, parameter)
Get all unique values for a given param from map_plate dictionary

4. get_well_params(mp_dictionary, well_name)
Get all parameters values for a given well
