### ISSUE TITLE
Saving information about program execution.

### ISSUE THREAD

**Issue by Setnea** [stork119/PathwayPackage#68]
“Auto-save” of information about paths to configuration_input and logs. IPIQA will provide options to save them into specific location thanks to new define variable (parameter) in config_dict.

- output folder name format : 
  <xml_settings_name>-<date>
- output path
  - default - working directory
  - defined by user in config_dict

**Comment by stork119** [comment]
Firstly, make simplified version: 

```
try:
    WORKFLOW EXECUTION
catch:
    ERROR PRINTING
save_log_to_output_file
```

**Comment by stork119** [comment]
Files are saved in improper folder

**Comment by Setnea** [comment]
? They're saved in main software directory, its default destination for most of bioinf tools.

**Comment by Setnea** [comment]
Info about execution is always saved in working directory, I will add option to define output_path in xml settings.

**Comment by Setnea** [comment]
Works properly, can be closed.
