### ISSUE TITLE
[XML] Type control of XML parameters

### ISSUE THREAD

**Issue by Setnea** [stork119/PathwayPackage#69]
Adding support for known parameters for all tasks and configuration dictionary. New functions will verify presence and format of all required variables (i.e. if its integer in case of number_of_cores parameter in config_dict). Documentation describing all mandatory/optional parameters for each task should be provided.

**Comment by stork119** [comment]
@Setnea I haven't seen type control in program.

**Comment by Setnea** [comment]
You're right. I was inatentive.
